name: Deploy to EC2

on:
  push:
    branches:
      - master  # Adjust to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java with the specified version and distribution
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the project
      - name: Build with Maven
        run: ./mvnw clean package

      # Step 4: Copy the JAR file to EC2 instance using SSH
      - name: Copy JAR to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa target/calculatorapi-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:~/myapp

      # Step 5: SSH into EC2 and restart the application
      - name: Restart application on EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
            # Navigate to the application directory
            cd ~/myapp
            # Stop any running instances of the app (if applicable)
            pkill -f 'java -jar' || true
            # Start the application
            nohup java -jar calculatorapi-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
          EOF
